# community_bridge: PaulPham157-Profile
github: [paulpham157]
# issuehunt: paulpham157
ko_fi: paulpham157
# liberapay: paulpham157
# open_collective: paulpham157
patreon: PaulPham157
# tidelift: PLATFORM-NAME/PACKAGE-NAME
# polar: paulpham157
# buy_me_a_coffee: paulpham157
# thanks_dev: u/gh/paulpham157
custom: [
  'https://www.paypal.me/hungpham2302',
  'https://github.com/paulpham157/paulpham157/blob/main/vn_banking_transfer_paulpham157_PHAM_DINH_HUNG.jpg',
  # 'https://www.paypal.me/paulpham157',
]
